global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Account Service
  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:5002']
    metrics_path: '/metrics'

  # Transaction Service
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:5003']
    metrics_path: '/metrics'

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5004']
    metrics_path: '/metrics'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']